# Generated by Django 4.0.6 on 2024-12-19 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_produced', models.PositiveIntegerField()),
                ('date_produced', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('bags_returned', models.PositiveIntegerField(default=0)),
                ('bags_pushed_to_sales', models.PositiveIntegerField(default=0)),
                ('expense_title', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_expense', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses_receipts/')),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
