# Generated by Django 4.0.6 on 2024-12-23 06:41

from django.db import migrations, models
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Operations Manager', 'Operations Manager')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='operationsrecord',
            constraint=models.CheckConstraint(check=models.Q(('bags_pushed_to_sales__lte', django.db.models.expressions.F('bags_produced'))), name='bags_pushed_to_sales_lte_bags_produced'),
        ),
    ]
