# Generated by Django 4.0.6 on 2024-12-23 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_sold', models.PositiveIntegerField()),
                ('bags_returned', models.PositiveIntegerField(default=0)),
                ('date_of_sale', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Sales Record',
                'verbose_name_plural': 'Sales Records',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Operations Manager', 'Operations Manager'), ('Sales', 'sales'), ('Driver', 'driver'), ('Bagger', 'bagger'), ('Cleaner', 'cleaner'), ('Motor boy', 'motor boy'), ('Security', 'security')], max_length=50),
        ),
    ]
