# Generated by Django 4.0.6 on 2024-12-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='bags_received_from_production',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='keystone',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='moniepoint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='zenith',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
