# Generated by Django 4.0.6 on 2025-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_salesrecord_cash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesrecord',
            options={},
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
