# Generated by Django 4.0.6 on 2025-01-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_salesrecord_options_salesrecord_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='applied_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
