# Generated by Django 4.0.6 on 2025-01-22 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_salesrecord_applied_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_expense', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses_receipts/')),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='operationsrecord',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='operationsrecord',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='operationsrecord',
            name='date_of_expense',
        ),
        migrations.RemoveField(
            model_name='operationsrecord',
            name='expense_title',
        ),
        migrations.RemoveField(
            model_name='operationsrecord',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Finance', 'finance'), ('Operations Manager', 'Operations Manager'), ('Sales', 'sales'), ('Driver', 'driver'), ('Bagger', 'bagger'), ('Cleaner', 'cleaner'), ('Motor boy', 'motor boy'), ('Security', 'security'), ('Supervisor', 'supervisor')], max_length=50),
        ),
    ]
