# Generated by Django 4.0.6 on 2025-01-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_salesrecord_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsrecord',
            name='comments',
            field=models.TextField(blank=True, max_length=2035),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='comments',
            field=models.TextField(blank=True, max_length=2035),
        ),
        migrations.AlterField(
            model_name='finance',
            name='comments',
            field=models.TextField(blank=True, max_length=2035),
        ),
    ]
