# Generated by Django 4.0.6 on 2025-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_operationsrecord_comments_salesrecord_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='keystone',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='moniepoint',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='zenith',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
