# Generated by Django 4.0.6 on 2025-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_operationsrecord_bad_stereo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Finance', 'finance'), ('Operations Manager', 'Operations Manager'), ('Sales', 'sales'), ('Driver', 'driver'), ('Bagger', 'bagger'), ('Cleaner', 'cleaner'), ('Motor boy', 'motor boy'), ('Security', 'security'), ('Supervisor', 'supervisor'), ('Operator', 'operator'), ('Front desk', 'front desk')], max_length=50),
        ),
    ]
