# Generated by Django 4.0.6 on 2025-06-12 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_sold', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_sale', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('keystone', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('zenith', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('moniepoint', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comments', models.TextField(blank=True, max_length=2035)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_received', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('bags_sold', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date_of_sale', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('keystone', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('zenith', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('moniepoint', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comments', models.TextField(blank=True, max_length=2035)),
            ],
        ),
        migrations.RemoveField(
            model_name='finance',
            name='expense_title',
        ),
        migrations.AddField(
            model_name='finance',
            name='custom_expense_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('Fuel', 'fuel'), ('Diesel', 'diesel'), ('Vehicle repairs', 'vehicle_repairs'), ('Packaging bags', 'packaging_bags'), ('Stereo', 'stereo'), ('Fuel deposit', 'fuel deposit'), ('Audit fee', 'audit fee'), ('Generator repairs', 'generator repairs'), ('Imprest account', 'imprest account'), ('Others', 'others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operationsrecord',
            name='diesel_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operationsrecord',
            name='diesel_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Finance', 'finance'), ('Operations Manager', 'Operations Manager'), ('Production supervisor', 'production supervisor'), ('Sales', 'sales'), ('Driver', 'driver'), ('Bagger', 'bagger'), ('Cleaner', 'cleaner'), ('Motor boy', 'motor boy'), ('Security', 'security'), ('Supervisor', 'supervisor'), ('Operator', 'operator'), ('Front desk', 'front desk'), ('Store keeper', 'store keeper'), ('Boss', 'boss')], max_length=50),
        ),
    ]
