# Generated by Django 4.0.6 on 2025-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_specialsale_store_remove_finance_expense_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('Fuel', 'fuel'), ('Diesel', 'diesel'), ('Vehicle repairs', 'vehicle_repairs'), ('Packaging bags', 'packaging_bags'), ('Stereo', 'stereo'), ('Fuel deposit', 'fuel deposit'), ('Audit fee', 'audit fee'), ('Generator repairs', 'generator repairs'), ('Imprest account', 'imprest account'), ('Waybill', 'waybill'), ('Others', 'others')], max_length=50, null=True),
        ),
    ]
