# Generated by Django 4.0.6 on 2025-06-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_finance_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialsale',
            name='applied_discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='applied_discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
