# Generated by Django 4.0.6 on 2025-07-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_specialsale_applied_discount_store_applied_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
