# Generated by Django 4.0.6 on 2025-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsrecord',
            name='stereo_yeild',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
