# Generated by Django 4.0.6 on 2025-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_operationsrecord_stereo_yeild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Finance', 'finance'), ('Operations Manager', 'Operations Manager'), ('Production supervisor', 'production supervisor'), ('Sales manager', 'sales Manager'), ('Driver', 'driver'), ('Bagger', 'bagger'), ('Cleaner', 'cleaner'), ('Motor boy', 'motor boy'), ('Security', 'security'), ('Supervisor', 'supervisor'), ('Operator', 'operator'), ('Front desk', 'front desk'), ('Store keeper', 'store keeper'), ('Boss', 'boss')], max_length=50),
        ),
    ]
