# Generated by Django 4.0.6 on 2025-07-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_customuser_role'),
    ]

   