# Generated by Django 4.0.6 on 2025-07-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_operationsrecord_bags_pushed_to_sales_and_more'),
    ]

    # operations = [
    #     migrations.RemoveConstraint(
    #         model_name='operationsrecord',
    #         name='bags_pushed_to_sales_lte_bags_produced',
    #     ),
    # ]
