# Generated by Django 4.0.6 on 2025-08-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_operationsrecord_bags_pushed_to_sales_lte_bags_produced'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operationsrecord',
            name='bags_pushed_to_sales_lte_bags_produced',
        ),
        migrations.RemoveField(
            model_name='operationsrecord',
            name='bags_pushed_to_sales',
        ),
        migrations.RemoveField(
            model_name='operationsrecord',
            name='bags_returned',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='bags_received_from_production',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='bags_returned',
        ),
    ]
