# Generated by Django 4.0.6 on 2025-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_operationsrecord_bags_pushed_to_sales_lte_bags_produced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='damaged',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='law_enforcement',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='lost_to_rebagging',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='rebagged',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='to_umuahia',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
