# Generated by Django 4.0.6 on 2025-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_salesrecord_damaged_salesrecord_law_enforcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsrecord',
            name='cone',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
