# Generated by Django 4.0.6 on 2025-08-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_operationsrecord_cone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationsrecord',
            old_name='stereo_yeild',
            new_name='stereo_yield',
        ),
    ]
